-- 테이블 & 시퀀스 삭제
--DROP TABLE CHAMP_SKILLS_INFO CASCADE CONSTRAINTS;
--DROP TABLE HERO_SKILLS_INFO CASCADE CONSTRAINTS;
--DROP TABLE BOARD_LIKES CASCADE CONSTRAINTS;
--DROP TABLE REPLY_LIKES CASCADE CONSTRAINTS;
--DROP TABLE ITEM_LOG CASCADE CONSTRAINTS;
--DROP TABLE ITEM_WEIGHT CASCADE CONSTRAINTS;
--DROP TABLE ITEM_COMPATIBILITY CASCADE CONSTRAINTS;
--DROP TABLE WEAPON CASCADE CONSTRAINTS;
--DROP TABLE EQUIPMENT CASCADE CONSTRAINTS;
--DROP TABLE ATTACH_FILE CASCADE CONSTRAINTS;
--DROP TABLE PARTY_RECRUIT CASCADE CONSTRAINTS;
--DROP TABLE CHAMP_SKIN_INFO CASCADE CONSTRAINTS;
--DROP TABLE HERO_SKIN_INFO CASCADE CONSTRAINTS;
--DROP TABLE TALENT_INFO CASCADE CONSTRAINTS;
--DROP TABLE MAP_MARKER CASCADE CONSTRAINTS;
--DROP TABLE REPORT CASCADE CONSTRAINTS;
--DROP TABLE INQUIRY CASCADE CONSTRAINTS;
--DROP TABLE REPLY CASCADE CONSTRAINTS;
--DROP TABLE BOARD CASCADE CONSTRAINTS;
--DROP TABLE LOG_GG_USER CASCADE CONSTRAINTS;
--DROP TABLE ITEM_LIST CASCADE CONSTRAINTS;
--DROP TABLE Box_LIST CASCADE CONSTRAINTS;
--DROP TABLE CHAMP_INFO CASCADE CONSTRAINTS;
--DROP TABLE HERO_INFO CASCADE CONSTRAINTS;
--DROP TABLE BAG_ITEM_INFO CASCADE CONSTRAINTS;
--DROP TABLE RUNE_INFO CASCADE CONSTRAINTS;
--DROP TABLE MAP_INFO CASCADE CONSTRAINTS;
--DROP TABLE CATEGORY_TABLE CASCADE CONSTRAINTS;
--DROP TABLE BAG_ITEM_CATEGORY CASCADE CONSTRAINTS;
--DROP TABLE MARKER_CATEGORY CASCADE CONSTRAINTS;
--DROP TABLE GAME_CODE CASCADE CONSTRAINTS;
--DROP TABLE SPELL_INFO CASCADE CONSTRAINTS;
--DROP TABLE LOL_ITEM_INFO CASCADE CONSTRAINTS;
--DROP TABLE PATCHNOTE CASCADE CONSTRAINTS;
--DROP TABLE NOTICE CASCADE CONSTRAINTS;

--DROP SEQUENCE SEQ_USER_NO;
--DROP SEQUENCE SEQ_BOARD_NO;
--DROP SEQUENCE SEQ_REPLY_NO;
--DROP SEQUENCE SEQ_LOG_NO;
--DROP SEQUENCE SEQ_REPORT_NO;
--DROP SEQUENCE SEQ_INQUIRY_NO;
--DROP SEQUENCE SEQ_CATEGORY_NO;
--DROP SEQUENCE SEQ_RUNE_NO;
--DROP SEQUENCE SEQ_ITEM_NO;
--DROP SEQUENCE SEQ_CHAMP_NO;
--DROP SEQUENCE SEQ_CHAMP_SKIN_NO;
--DROP SEQUENCE SEQ_SPELL_NO;
--DROP SEQUENCE SEQ_TALENT_NO;
--DROP SEQUENCE SEQ_HERO_NO;
--DROP SEQUENCE SEQ_HERO_SKIN_NO;
--DROP SEQUENCE SEQ_MARKER_NO;
--DROP SEQUENCE SEQ_MAP_NO;
--DROP SEQUENCE SEQ_FILE_NO;
--DROP SEQUENCE SEQ_NOTICE_NO;

CREATE TABLE SPELL_INFO (
	SPELL_NO	NUMBER		NOT NULL,
	SPELL_NAME	VARCHAR2(50)		NULL,
	SPELL_INFO	VARCHAR2(1000)		NULL
);

COMMENT ON COLUMN SPELL_INFO.SPELL_NO IS '주문 번호(시퀀스 자동생성)';
COMMENT ON COLUMN SPELL_INFO.SPELL_NAME IS '주문 이름';
COMMENT ON COLUMN SPELL_INFO.SPELL_INFO IS '주문 설명';


CREATE TABLE BOARD_LIKES (
	USER_NO	NUMBER NOT NULL,
	BOARD_NO NUMBER NOT NULL
);

COMMENT ON COLUMN BOARD_LIKES.USER_NO IS '시퀀스 자동생성';
COMMENT ON COLUMN BOARD_LIKES.BOARD_NO IS '시퀀스 자동생성';

CREATE TABLE LOL_ITEM_INFO (
	ITEM_NO	NUMBER	NOT NULL,
	ITEM_NAME	VARCHAR2(100) NOT NULL,
	ITEM_PRICE	NUMBER NOT NULL,
	ITEM_INFO	VARCHAR2(1000) NULL,
	ITEM_IMG	VARCHAR2(500) NULL
);

COMMENT ON COLUMN LOL_ITEM_INFO.ITEM_NO IS '아이템 번호(시퀀스 자동생성)';
COMMENT ON COLUMN LOL_ITEM_INFO.ITEM_NAME IS '아이템 이름';
COMMENT ON COLUMN LOL_ITEM_INFO.ITEM_PRICE IS '아이템 가격';
COMMENT ON COLUMN LOL_ITEM_INFO.ITEM_INFO IS '아이템 설명';
COMMENT ON COLUMN LOL_ITEM_INFO.ITEM_IMG IS '아이템 이미지';

CREATE TABLE BOARD (
	BOARD_NO	NUMBER		NOT NULL,
	USER_NO	NUMBER		NOT NULL,
	CATEGORY_NO	NUMBER		NOT NULL,
	GAME_CODE	VARCHAR2(10)		NOT NULL,
	BOARD_TITLE	VARCHAR2(300)		NOT NULL,
	BOARD_CONTENT	CLOB		NOT NULL,
	POST_DATE	DATE	DEFAULT SYSDATE	NOT NULL,
	BOARD_CD	CHAR(1)	DEFAULT 'Y'	NOT NULL,
	READ_COUNT	NUMBER	DEFAULT 0	NOT NULL
);

COMMENT ON COLUMN BOARD.BOARD_NO IS '시퀀스 자동생성';
COMMENT ON COLUMN BOARD.USER_NO IS '시퀀스 자동생성';
COMMENT ON COLUMN BOARD.CATEGORY_NO IS '자유 , 공략';
COMMENT ON COLUMN BOARD.GAME_CODE IS 'LOL,OW,BG';
COMMENT ON COLUMN BOARD.BOARD_TITLE IS '글 제목';
COMMENT ON COLUMN BOARD.BOARD_CONTENT IS '글 내용';
COMMENT ON COLUMN BOARD.POST_DATE IS '글 작성시간';
COMMENT ON COLUMN BOARD.BOARD_CD IS '글 삭제여부';
COMMENT ON COLUMN BOARD.READ_COUNT IS '글 조회수';

CREATE TABLE PATCHNOTE (
	PATCHNOTE_NO	NUMBER		NOT NULL,
	GAME_CODE	VARCHAR2(10)		NOT NULL,
	TITLE	VARCHAR2(200)		NOT NULL,
	POST_DATE	DATE	DEFAULT SYSDATE	NOT NULL,
	PATCHNOTE_CONTENT	CLOB		NOT NULL
);

COMMENT ON COLUMN PATCHNOTE.PATCHNOTE_NO IS '시퀀스자동생성';
COMMENT ON COLUMN PATCHNOTE.GAME_CODE IS 'LOL,OW,BG';
COMMENT ON COLUMN PATCHNOTE.TITLE IS '글 번호';
COMMENT ON COLUMN PATCHNOTE.POST_DATE IS '디폴트 : SYSDATE';
COMMENT ON COLUMN PATCHNOTE.PATCHNOTE_CONTENT IS '패치노트 내용';

CREATE TABLE REPLY (
	REPLY_NO	NUMBER		NOT NULL,
    BOARD_NO   NUMBER   NOT NULL,
	USER_NO	NUMBER		NOT NULL,
	REPLY_CONTENT	CLOB		NOT NULL,
	REPLY_DATE	DATE	DEFAULT SYSDATE	NOT NULL,
	STATUS	CHAR(1)	DEFAULT 'Y'	NOT NULL,
	PARENT_REPLY_NO	NUMBER		NULL
);

COMMENT ON COLUMN REPLY.REPLY_NO IS '시퀀스 자동생성';
COMMENT ON COLUMN REPLY.USER_NO IS '시퀀스 자동생성';
COMMENT ON COLUMN REPLY.REPLY_CONTENT IS '글 내용';
COMMENT ON COLUMN REPLY.REPLY_DATE IS '댓글 작성시간';
COMMENT ON COLUMN REPLY.STATUS IS '댓글 삭제여부';
COMMENT ON COLUMN REPLY.PARENT_REPLY_NO IS '대댓글 구현';

CREATE TABLE MARKER_CATEGORY (
	CATEGORY_NO	NUMBER		NOT NULL,
	CATEGORY_NAME	VARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN MARKER_CATEGORY.CATEGORY_NO IS '카테고리 번호';
COMMENT ON COLUMN MARKER_CATEGORY.CATEGORY_NAME IS '카테고리 이름';

CREATE TABLE WEAPON (
	ITEM_NO	NUMBER		NOT NULL,
	CATEGORY_NO	NUMBER		NOT NULL,
	ITEM_DAMAGE	NUMBER		NOT NULL,
	ITEM_AMMO_COUNT	NUMBER		NOT NULL,
	ITEM_AMMO_TYPE	VARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN WEAPON.ITEM_NO IS '아이템 번호';
COMMENT ON COLUMN WEAPON.CATEGORY_NO IS '1(무기), 2(부착물), 3(탄약),, 4(방어구), 5(소모품)';
COMMENT ON COLUMN WEAPON.ITEM_DAMAGE IS '데미지';
COMMENT ON COLUMN WEAPON.ITEM_AMMO_COUNT IS '장탄수';
COMMENT ON COLUMN WEAPON.ITEM_AMMO_TYPE IS '사용 탄약';

CREATE TABLE NOTICE (
	NOTICE_NO	NUMBER		NOT NULL,
	TITLE	VARCHAR2(200)		NOT NULL,
	POST_DATE	DATE	DEFAULT SYSDATE	NOT NULL,
	NOTICE_CONTENT	CLOB NOT NULL
);

COMMENT ON COLUMN NOTICE.NOTICE_NO IS '시퀀스 자동생성';
COMMENT ON COLUMN NOTICE.TITLE IS '글 제목';
COMMENT ON COLUMN NOTICE.POST_DATE IS '디폴트 : SYSDATE';
COMMENT ON COLUMN NOTICE.NOTICE_CONTENT IS '공지사항 내용';

CREATE TABLE ITEM_LOG (
	LOG_NO	NUMBER		NOT NULL,
	ITEM_NO	NUMBER		NOT NULL,
	BOX_NO	NUMBER		NOT NULL
);

COMMENT ON COLUMN ITEM_LOG.LOG_NO IS '로그 번호';
COMMENT ON COLUMN ITEM_LOG.ITEM_NO IS '아이템 번호';
COMMENT ON COLUMN ITEM_LOG.BOX_NO IS '상자 번호';

CREATE TABLE LOG_GG_USER (
	USER_NO	NUMBER		NOT NULL,
	USER_ID	VARCHAR2(100)		NOT NULL,
	USER_PW	VARCHAR2(200)		NOT NULL,
	USER_NAME	VARCHAR2(50)		NOT NULL,
	STATUS	CHAR(1)	DEFAULT 'Y'	NOT NULL,
	WITHDRAW	CHAR(1)	DEFAULT 'N'	NOT NULL,
	ENROLL_DATE	DATE	DEFAULT SYSDATE	NOT NULL,
    MODIFIED_DATE DATE  NULL,
	USER_ROLE	CHAR(1)	DEFAULT 'U'	NOT NULL
);

COMMENT ON COLUMN LOG_GG_USER.USER_NO IS '시퀀스 자동생성';
COMMENT ON COLUMN LOG_GG_USER.USER_ID IS '아이디';
COMMENT ON COLUMN LOG_GG_USER.USER_PW IS '비밀번호';
COMMENT ON COLUMN LOG_GG_USER.USER_NAME IS '닉네임';
COMMENT ON COLUMN LOG_GG_USER.STATUS IS '로그인 Y , N';
COMMENT ON COLUMN LOG_GG_USER.WITHDRAW IS '탈퇴여부';
COMMENT ON COLUMN LOG_GG_USER.ENROLL_DATE IS '디폴트 : SYSDATE';
COMMENT ON COLUMN LOG_GG_USER.MODIFIED_DATE IS '수정날짜';
COMMENT ON COLUMN LOG_GG_USER.USER_ROLE IS '회원(U), 관리자(A)';

CREATE TABLE CHAMP_INFO (
	CHAMP_NO	NUMBER		NOT NULL,
	CHAMP_NAME	VARCHAR2(100)		NOT NULL,
	CHAMP_POSITION	VARCHAR2(30)		NOT NULL,
	CHAMP_ROLES	VARCHAR2(30)		NULL,
	CHAMP_IMG	VARCHAR2(500)		NULL
);

COMMENT ON COLUMN CHAMP_INFO.CHAMP_NO IS '챔피언 번호(시퀀스 자동생성)';
COMMENT ON COLUMN CHAMP_INFO.CHAMP_NAME IS '챔피언 이름';
COMMENT ON COLUMN CHAMP_INFO.CHAMP_POSITION IS '챔피언 역할군(암살자,원거리 딜러, 탱커 등)';
COMMENT ON COLUMN CHAMP_INFO.CHAMP_ROLES IS '탑,정글,미드,원딜,서폿';
COMMENT ON COLUMN CHAMP_INFO.CHAMP_IMG IS '챔피언 이미지';

CREATE TABLE CHAMP_SKIN_INFO (
	CHAMP_SKIN_NO	NUMBER		NOT NULL,
	CHAMP_NO	NUMBER		NOT NULL,
	CHAMP_SKIN_NAME	VARCHAR2(100)		NOT NULL,
	CHAMP_SKIN_IMG	VARCHAR2(500)		NULL
);

COMMENT ON COLUMN CHAMP_SKIN_INFO.CHAMP_SKIN_NO IS '스킨 번호(시퀀스 자동생성)';
COMMENT ON COLUMN CHAMP_SKIN_INFO.CHAMP_NO IS '챔피언 번호(시퀀스 자동생성)';
COMMENT ON COLUMN CHAMP_SKIN_INFO.CHAMP_SKIN_NAME IS '챔피언 스킨 이름';
COMMENT ON COLUMN CHAMP_SKIN_INFO.CHAMP_SKIN_IMG IS '챔피언 이미지';

CREATE TABLE ATTACH_FILE (
	FILE_NO	NUMBER		NOT NULL,
	BOARD_NO	NUMBER		NOT NULL,
	GAME_CODE	VARCHAR2(10)		NOT NULL,
	ORIGIN_NAME	VARCHAR2(255)		NOT NULL,
	CHANGE_NAME	VARCHAR2(255)		NOT NULL,
	FILE_PATH	VARCHAR2(500)		NOT NULL,
	FILE_EXT	VARCHAR2(50)		NOT NULL,
	FILE_SIZE	NUMBER		NOT NULL
);
COMMENT ON COLUMN ATTACH_FILE.FILE_NO IS '파일 번호';
COMMENT ON COLUMN ATTACH_FILE.BOARD_NO IS '시퀀스 자동생성';
COMMENT ON COLUMN ATTACH_FILE.GAME_CODE IS 'LOL,OW,BG';
COMMENT ON COLUMN ATTACH_FILE.ORIGIN_NAME IS '첨부파일 원본 이름';
COMMENT ON COLUMN ATTACH_FILE.CHANGE_NAME IS '첨부파일 바뀐 이름';
COMMENT ON COLUMN ATTACH_FILE.FILE_PATH IS '파일 경로';
COMMENT ON COLUMN ATTACH_FILE.FILE_EXT IS '파일 확장자';
COMMENT ON COLUMN ATTACH_FILE.FILE_SIZE IS '파일 크기';

CREATE TABLE ITEM_WEIGHT (
	ITEM_NO	NUMBER		NOT NULL,
	BOX_NO	NUMBER		NOT NULL,
	WEIGHT	NUMBER		NOT NULL
);

COMMENT ON COLUMN ITEM_WEIGHT.ITEM_NO IS '아이템 번호';
COMMENT ON COLUMN ITEM_WEIGHT.BOX_NO IS '상자 번호';
COMMENT ON COLUMN ITEM_WEIGHT.WEIGHT IS '확률';

CREATE TABLE MAP_MARKER (
	MARKER_NO	NUMBER		NOT NULL,
	COORD_X	NUMBER		NOT NULL,
	COORD_Y	NUMBER		NOT NULL,
	MARKER_IMG	VARCHAR2(500)		NOT NULL,
	MAP_NO	NUMBER		NOT NULL,
	CATEGORY_NO	NUMBER		NOT NULL
);

COMMENT ON COLUMN MAP_MARKER.MARKER_NO IS '마커 번호';
COMMENT ON COLUMN MAP_MARKER.COORD_X IS 'X 좌표';
COMMENT ON COLUMN MAP_MARKER.COORD_Y IS 'Y 좌표';
COMMENT ON COLUMN MAP_MARKER.MARKER_IMG IS '마커 이미지';
COMMENT ON COLUMN MAP_MARKER.MAP_NO IS '맵 번호';
COMMENT ON COLUMN MAP_MARKER.CATEGORY_NO IS '카테고리 번호';

CREATE TABLE HERO_INFO (
	HERO_NO	NUMBER		NOT NULL,
	HERO_NAME	VARCHAR2(100)		NOT NULL,
	HERO_INTRO	VARCHAR2(100)		NULL,
	HERO_HP	NUMBER	DEFAULT 0	NOT NULL,
	HERO_POSITION	VARCHAR2(30)		NOT NULL
);

COMMENT ON COLUMN HERO_INFO.HERO_NO IS '영웅 번호(시퀀스 자동생성)';
COMMENT ON COLUMN HERO_INFO.HERO_NAME IS '영웅 이름';
COMMENT ON COLUMN HERO_INFO.HERO_INTRO IS '영웅 소개';
COMMENT ON COLUMN HERO_INFO.HERO_HP IS '영웅 HP';
COMMENT ON COLUMN HERO_INFO.HERO_POSITION IS '영웅 포지션(힐러,딜러,탱커 등)';

CREATE TABLE PARTY_RECRUIT (
	BOARD_NO	NUMBER		NOT NULL,
	CAPACITY	NUMBER		NOT NULL,
	TIER	VARCHAR2(20)		NOT NULL,
	PARTY_CURRENT	VARCHAR2(20) DEFAULT '모집 중'		NOT NULL,
	PREFER_MAP	VARCHAR2(30)	DEFAULT '해당 없음'	NOT NULL
);

COMMENT ON COLUMN PARTY_RECRUIT.BOARD_NO IS '시퀀스 자동생성';
COMMENT ON COLUMN PARTY_RECRUIT.CAPACITY IS '모집 인원수';
COMMENT ON COLUMN PARTY_RECRUIT.TIER IS '티어';
COMMENT ON COLUMN PARTY_RECRUIT.PARTY_CURRENT IS '모집 중 , 모집 완료';
COMMENT ON COLUMN PARTY_RECRUIT.PREFER_MAP IS '선호 맵';

CREATE TABLE TALENT_INFO (
	TALENT_NO	NUMBER		NOT NULL,
	RUNE_NO	NUMBER		NOT NULL,
	TALENT_NAME	VARCHAR2(50)		NOT NULL,
	TALENT_INFO	VARCHAR2(300)		NULL,
	TALENT_IMG	VARCHAR2(500)		NULL
);

COMMENT ON COLUMN TALENT_INFO.TALENT_NO IS '특성 번호(시퀀스 자동생성)';
COMMENT ON COLUMN TALENT_INFO.RUNE_NO IS '룬 번호(시퀀스 자동생성)';
COMMENT ON COLUMN TALENT_INFO.TALENT_NAME IS '특성 이름';
COMMENT ON COLUMN TALENT_INFO.TALENT_INFO IS '특성 설명';
COMMENT ON COLUMN TALENT_INFO.TALENT_IMG IS '특성 이미지';

CREATE TABLE BAG_ITEM_INFO (
	ITEM_NO	NUMBER		NOT NULL,
	CATEGORY_NO	NUMBER		NOT NULL,
	ITEM_NAME	VARCHAR2(100)		NOT NULL,
	ITEM_INFO	VARCHAR2(300)		NULL,
	ITEM_IMG	VARCHAR2(500)		NULL,
	ITEM_TYPE	VARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN BAG_ITEM_INFO.ITEM_NO IS '아이템 번호';
COMMENT ON COLUMN BAG_ITEM_INFO.CATEGORY_NO IS '1(무기), 2(부착물), 3(탄약),, 4(방어구), 5(소모품)';
COMMENT ON COLUMN BAG_ITEM_INFO.ITEM_NAME IS '아이템 이름';
COMMENT ON COLUMN BAG_ITEM_INFO.ITEM_INFO IS '아이템 설명';
COMMENT ON COLUMN BAG_ITEM_INFO.ITEM_IMG IS '아이템 이미지';
COMMENT ON COLUMN BAG_ITEM_INFO.ITEM_TYPE IS '아이템 종류';

CREATE TABLE EQUIPMENT (
	ITEM_NO	NUMBER		NOT NULL,
	CATEGORY_NO	NUMBER		NOT NULL,
	ITEM_DURABILITY	NUMBER		NULL,
	ITEM_DAMAGE_REDUCTION	NUMBER		NULL
);

COMMENT ON COLUMN EQUIPMENT.ITEM_NO IS '아이템 번호';
COMMENT ON COLUMN EQUIPMENT.CATEGORY_NO IS '1(무기), 2(부착물), 3(탄약),, 4(방어구), 5(소모품)';
COMMENT ON COLUMN EQUIPMENT.ITEM_DURABILITY IS '내구도';
COMMENT ON COLUMN EQUIPMENT.ITEM_DAMAGE_REDUCTION IS '피해감소';

CREATE TABLE MAP_INFO (
	MAP_NO	NUMBER		NOT NULL,
	MAP_NAME	VARCHAR2(50)		NOT NULL,
	MAP_IMG	VARCHAR2(500)		NOT NULL
);

COMMENT ON COLUMN MAP_INFO.MAP_NO IS '맵 번호';
COMMENT ON COLUMN MAP_INFO.MAP_NAME IS '맵 이름';
COMMENT ON COLUMN MAP_INFO.MAP_IMG IS '맵 이미지';

CREATE TABLE RUNE_INFO (
	RUNE_NO	NUMBER		NOT NULL,
	RUNE_NAME	VARCHAR2(30)		NOT NULL,
	RUNE_INFO	VARCHAR2(200)		NULL,
	RUNE_IMG	VARCHAR2(500)		NULL
);

COMMENT ON COLUMN RUNE_INFO.RUNE_NO IS '룬 번호(시퀀스 자동생성)';
COMMENT ON COLUMN RUNE_INFO.RUNE_NAME IS '룬 이름';
COMMENT ON COLUMN RUNE_INFO.RUNE_INFO IS '룬 설명';
COMMENT ON COLUMN RUNE_INFO.RUNE_IMG IS '룬 이미지';

CREATE TABLE ITEM_COMPATIBILITY (
	ITEM_NO	NUMBER		NOT NULL,
	CATEGORY_NO	NUMBER		NOT NULL,
	PART_ITEM_NO	NUMBER		NOT NULL,
	PART_CATEGORY_NO	NUMBER		NOT NULL,
	WEAPON_ITEM_NO	NUMBER		NOT NULL,
	WEAPON_CATEGORY_NO	NUMBER		NOT NULL
);

COMMENT ON COLUMN ITEM_COMPATIBILITY.ITEM_NO IS '아이템 번호';
COMMENT ON COLUMN ITEM_COMPATIBILITY.CATEGORY_NO IS '1(무기), 2(부착물), 3(탄약),, 4(방어구), 5(소모품)';
COMMENT ON COLUMN ITEM_COMPATIBILITY.PART_ITEM_NO IS '파츠 아이템 번호';
COMMENT ON COLUMN ITEM_COMPATIBILITY.PART_CATEGORY_NO IS '파츠 카테고리 번호';
COMMENT ON COLUMN ITEM_COMPATIBILITY.WEAPON_ITEM_NO IS '무기 아이템 번호';
COMMENT ON COLUMN ITEM_COMPATIBILITY.WEAPON_CATEGORY_NO IS '무기 카테고리 번호';

CREATE TABLE Box_LIST (
	BOX_NO	NUMBER		NOT NULL,
	BOX_NAME	VARCHAR2(100)		NOT NULL,
	BOX_TYPE	VARCHAR2(100)		NOT NULL,
	START_DATE	DATE   DEFAULT SYSDATE		NOT NULL,
	END_DATE	DATE	DEFAULT SYSDATE 	NOT NULL
);

COMMENT ON COLUMN Box_LIST.BOX_NO IS '상자 번호';
COMMENT ON COLUMN Box_LIST.BOX_NAME IS '상자 이름';
COMMENT ON COLUMN Box_LIST.BOX_TYPE IS '상자 종류';
COMMENT ON COLUMN Box_LIST.START_DATE IS '뽑기 기간 시작일';
COMMENT ON COLUMN Box_LIST.END_DATE IS '뽑기 기간 종료일';

CREATE TABLE HERO_SKIN_INFO (
	HERO_SKIN_NO	NUMBER		NOT NULL,
	HERO_NO	NUMBER		NOT NULL,
	HERO_SKIN_NAME	VARCHAR2(200)		NOT NULL,
	HERO_SKIN_IMG	VARCHAR2(500)		NULL
);

COMMENT ON COLUMN HERO_SKIN_INFO.HERO_SKIN_NO IS '스킨 번호(시퀀스 자동생성)';
COMMENT ON COLUMN HERO_SKIN_INFO.HERO_NO IS '영웅 번호(시퀀스 자동생성)';
COMMENT ON COLUMN HERO_SKIN_INFO.HERO_SKIN_NAME IS '챔피언 스킨 이름';
COMMENT ON COLUMN HERO_SKIN_INFO.HERO_SKIN_IMG IS '챔피언 이미지';

CREATE TABLE REPORT (
	REPORT_NO	NUMBER		NOT NULL,
	USER_NO	NUMBER		NOT NULL,
	BOARD_NO	NUMBER		NULL,
	REPLY_NO	NUMBER		NULL,
	REPORT_CONTENT	CLOB		NOT NULL,
	STATUS	CHAR(1)	DEFAULT 'N'	NOT NULL,
	DONE_DATE	DATE	NULL,
	REPORT_TYPE	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN REPORT.REPORT_NO IS '신고 글 번호';
COMMENT ON COLUMN REPORT.USER_NO IS '시퀀스 자동생성';
COMMENT ON COLUMN REPORT.BOARD_NO IS '시퀀스 자동생성';
COMMENT ON COLUMN REPORT.REPLY_NO IS '시퀀스 자동생성';
COMMENT ON COLUMN REPORT.REPORT_CONTENT IS '신고 내용';
COMMENT ON COLUMN REPORT.STATUS IS 'Y or N';
COMMENT ON COLUMN REPORT.DONE_DATE IS '처리완료시간';
COMMENT ON COLUMN REPORT.REPORT_TYPE IS '글,댓글,유저';

CREATE TABLE INQUIRY (
	BOARD_NO	NUMBER		NOT NULL,
	USER_NO	NUMBER		NOT NULL,
	USER_NAME	VARCHAR2(50)		NOT NULL,
	BOARD_CONTENT	CLOB	NOT NULL,
	BOARD_TITLE	VARCHAR2(100)		NOT NULL,
	POST_DATE	DATE	DEFAULT SYSDATE	NOT NULL,
	ANSWER_STATUS	CHAR(1)	DEFAULT 'W'	NOT NULL,
	REASON	VARCHAR2(100)		NOT NULL,
	ANSWER	CLOB DEFAULT '관리자의 답변을 기다려주세요.'  NOT NULL
);

COMMENT ON COLUMN INQUIRY.BOARD_NO IS '시퀀스 자동생성';
COMMENT ON COLUMN INQUIRY.USER_NO IS '시퀀스 자동생성';
COMMENT ON COLUMN INQUIRY.USER_NAME IS '닉네임';
COMMENT ON COLUMN INQUIRY.BOARD_CONTENT IS '글 내용';
COMMENT ON COLUMN INQUIRY.BOARD_TITLE IS '글 제목';
COMMENT ON COLUMN INQUIRY.POST_DATE IS '글 작성시간';
COMMENT ON COLUMN INQUIRY.ANSWER_STATUS IS '답변대기(W), 답변완료(C)';
COMMENT ON COLUMN INQUIRY.REASON IS '문의사유';
COMMENT ON COLUMN INQUIRY.ANSWER IS '관리자의 답변 내용';

CREATE TABLE GAME_CODE (
	GAME_CODE	VARCHAR2(10)		NOT NULL,
	GAME_NAME	VARCHAR2(50)		NOT NULL
);

COMMENT ON COLUMN GAME_CODE.GAME_CODE IS 'LOL,OW,BG';
COMMENT ON COLUMN GAME_CODE.GAME_NAME IS '게임 이름';

CREATE TABLE ITEM_LIST (
	ITEM_NO	NUMBER		NOT NULL,
	ITEM_NAME	VARCHAR2(100)		NOT NULL,
	ITEM_GRADE	VARCHAR2(30)		NOT NULL,
	ITEM_TYPE	VARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN ITEM_LIST.ITEM_NO IS '아이템 번호';
COMMENT ON COLUMN ITEM_LIST.ITEM_NAME IS '아이템 이름';
COMMENT ON COLUMN ITEM_LIST.ITEM_GRADE IS '아이템 등급';
COMMENT ON COLUMN ITEM_LIST.ITEM_TYPE IS '아이템 종류';

CREATE TABLE CATEGORY_TABLE (
	CATEGORY_NO	NUMBER		NOT NULL,
	GAME_CODE	VARCHAR2(10)		NOT NULL,
	CATEGORY_NAME	VARCHAR2(50)		NOT NULL,
	PARENT_CATEGORY_NO	NUMBER		NULL
);

COMMENT ON COLUMN CATEGORY_TABLE.CATEGORY_NO IS '시퀀스 자동생성';
COMMENT ON COLUMN CATEGORY_TABLE.GAME_CODE IS 'LOL,OW,BG';
COMMENT ON COLUMN CATEGORY_TABLE.CATEGORY_NAME IS '자유 게시판, 공략 게시판';
COMMENT ON COLUMN CATEGORY_TABLE.PARENT_CATEGORY_NO IS 'ex) 게시판 -> 자유, 공략 게시판';

CREATE TABLE BAG_ITEM_CATEGORY (
	CATEGORY_NO	NUMBER		NOT NULL,
	CATEGORY_NAME	VARCHAR2(100)		NOT NULL,
	CATEGORY_IMG	VARCHAR2(500)		NOT NULL
);

COMMENT ON COLUMN BAG_ITEM_CATEGORY.CATEGORY_NO IS '1(무기), 2(부착물), 3(탄약),, 4(방어구), 5(소모품)';
COMMENT ON COLUMN BAG_ITEM_CATEGORY.CATEGORY_NAME IS '카테고리 이름';
COMMENT ON COLUMN BAG_ITEM_CATEGORY.CATEGORY_IMG IS '카테고리 이미지';

CREATE TABLE REPLY_LIKES (
	REPLY_NO	NUMBER		NOT NULL,
	USER_NO	NUMBER		NOT NULL
);

COMMENT ON COLUMN REPLY_LIKES.REPLY_NO IS '시퀀스 자동생성';
COMMENT ON COLUMN REPLY_LIKES.USER_NO IS '시퀀스 자동생성';

-- 제약조건 unique
ALTER TABLE LOG_GG_USER ADD CONSTRAINT UK_LOG_USER_NAME UNIQUE(
    USER_NAME
);

ALTER TABLE LOG_GG_USER ADD CONSTRAINT UK_LOG_USER_ID UNIQUE(
    USER_ID
);

-- 제약조건 check
ALTER TABLE LOG_GG_USER ADD CONSTRAINT CK_LG_STATUS CHECK(
    STATUS IN ('Y', 'N')
);

ALTER TABLE LOG_GG_USER ADD CONSTRAINT CK_LG_WITHDRAW CHECK(
    WITHDRAW IN ('Y', 'N')
);

ALTER TABLE LOG_GG_USER ADD CONSTRAINT CK_LG_ROLE CHECK(
    USER_ROLE IN ('U', 'A')
);

ALTER TABLE INQUIRY ADD CONSTRAINT CK_INQ_STATUS CHECK(
    ANSWER_STATUS IN ('W', 'C')
);

ALTER TABLE REPORT ADD CONSTRAINT CK_REPORT_STATUS CHECK(
    STATUS IN ('Y', 'N')
);

ALTER TABLE REPLY ADD CONSTRAINT CK_REPLY_STATUS CHECK(
    STATUS IN ('Y', 'N')
);

ALTER TABLE BOARD ADD CONSTRAINT CK_BOARD_CD CHECK(
    BOARD_CD IN ('Y', 'N')
);

ALTER TABLE PARTY_RECRUIT ADD CONSTRAINT CK_PARTY_CURRENT CHECK(
    PARTY_CURRENT IN ('모집 중', '모집 완료')
);

-- 제약조건 pk/fk
ALTER TABLE SPELL_INFO ADD CONSTRAINT PK_SPELL_INFO PRIMARY KEY (
	SPELL_NO
);

ALTER TABLE BOARD_LIKES ADD CONSTRAINT PK_BOARD_LIKES PRIMARY KEY (
	USER_NO,
	BOARD_NO
);

ALTER TABLE LOL_ITEM_INFO ADD CONSTRAINT PK_LOL_ITEM_INFO PRIMARY KEY (
	ITEM_NO
);

ALTER TABLE BOARD ADD CONSTRAINT PK_BOARD PRIMARY KEY (
	BOARD_NO
);

ALTER TABLE PATCHNOTE ADD CONSTRAINT PK_PATCHNOTE PRIMARY KEY (
	PATCHNOTE_NO
);

ALTER TABLE REPLY ADD CONSTRAINT PK_REPLY PRIMARY KEY (
	REPLY_NO
);

ALTER TABLE MARKER_CATEGORY ADD CONSTRAINT PK_MARKER_CATEGORY PRIMARY KEY (
	CATEGORY_NO
);

ALTER TABLE WEAPON ADD CONSTRAINT PK_WEAPON PRIMARY KEY (
	ITEM_NO,
	CATEGORY_NO
);

ALTER TABLE NOTICE ADD CONSTRAINT PK_NOTICE PRIMARY KEY (
	NOTICE_NO
);

ALTER TABLE ITEM_LOG ADD CONSTRAINT PK_ITEM_LOG PRIMARY KEY (
	LOG_NO
);

ALTER TABLE LOG_GG_USER ADD CONSTRAINT PK_LOG_GG_USER PRIMARY KEY (
	USER_NO
);

ALTER TABLE CHAMP_INFO ADD CONSTRAINT PK_CHAMP_INFO PRIMARY KEY (
	CHAMP_NO
);

ALTER TABLE CHAMP_SKIN_INFO ADD CONSTRAINT PK_CHAMP_SKIN_INFO PRIMARY KEY (
	CHAMP_SKIN_NO,
	CHAMP_NO
);

ALTER TABLE ATTACH_FILE ADD CONSTRAINT PK_ATTACH_FILE PRIMARY KEY (
	FILE_NO
);

ALTER TABLE ITEM_WEIGHT ADD CONSTRAINT PK_ITEM_WEIGHT PRIMARY KEY (
	ITEM_NO,
	BOX_NO
);

ALTER TABLE MAP_MARKER ADD CONSTRAINT PK_MAP_MARKER PRIMARY KEY (
	MARKER_NO
);

ALTER TABLE HERO_INFO ADD CONSTRAINT PK_HERO_INFO PRIMARY KEY (
	HERO_NO
);

ALTER TABLE PARTY_RECRUIT ADD CONSTRAINT PK_PARTY_RECRUIT PRIMARY KEY (
	BOARD_NO
);

ALTER TABLE TALENT_INFO ADD CONSTRAINT PK_TALENT_INFO PRIMARY KEY (
	TALENT_NO,
	RUNE_NO
);

ALTER TABLE BAG_ITEM_INFO ADD CONSTRAINT PK_BAG_ITEM_INFO PRIMARY KEY (
	ITEM_NO,
	CATEGORY_NO
);

ALTER TABLE EQUIPMENT ADD CONSTRAINT PK_EQUIPMENT PRIMARY KEY (
	ITEM_NO,
	CATEGORY_NO
);

ALTER TABLE MAP_INFO ADD CONSTRAINT PK_MAP_INFO PRIMARY KEY (
	MAP_NO
);

ALTER TABLE RUNE_INFO ADD CONSTRAINT PK_RUNE_INFO PRIMARY KEY (
	RUNE_NO
);

ALTER TABLE Box_LIST ADD CONSTRAINT PK_BOX_LIST PRIMARY KEY (
	BOX_NO
);

ALTER TABLE HERO_SKIN_INFO ADD CONSTRAINT PK_HERO_SKIN_INFO PRIMARY KEY (
	HERO_SKIN_NO,
	HERO_NO
);

ALTER TABLE REPORT ADD CONSTRAINT PK_REPORT PRIMARY KEY (
	REPORT_NO
);

ALTER TABLE INQUIRY ADD CONSTRAINT PK_INQUIRY PRIMARY KEY (
	BOARD_NO
);

ALTER TABLE GAME_CODE ADD CONSTRAINT PK_GAME_CODE PRIMARY KEY (
	GAME_CODE
);

ALTER TABLE ITEM_LIST ADD CONSTRAINT PK_ITEM_LIST PRIMARY KEY (
	ITEM_NO
);

ALTER TABLE CATEGORY_TABLE ADD CONSTRAINT PK_CATEGORY_TABLE PRIMARY KEY (
	CATEGORY_NO,
	GAME_CODE
);

ALTER TABLE BAG_ITEM_CATEGORY ADD CONSTRAINT PK_BAG_ITEM_CATEGORY PRIMARY KEY (
	CATEGORY_NO
);

ALTER TABLE REPLY_LIKES ADD CONSTRAINT PK_REPLY_LIKES PRIMARY KEY (
	REPLY_NO,
	USER_NO
);

ALTER TABLE BOARD_LIKES ADD CONSTRAINT FK_LIKES_USER_NO FOREIGN KEY (
	USER_NO
)
REFERENCES LOG_GG_USER (
	USER_NO
);

ALTER TABLE BOARD_LIKES ADD CONSTRAINT FK_LIKES_BOARD_NO FOREIGN KEY (
	BOARD_NO
)
REFERENCES BOARD (
	BOARD_NO
);

ALTER TABLE BOARD ADD CONSTRAINT FK_BOARD_USER_NO FOREIGN KEY (
	USER_NO
)
REFERENCES LOG_GG_USER (
	USER_NO
);

ALTER TABLE BOARD ADD CONSTRAINT FK_BOARD_CAT_INFO FOREIGN KEY (
	CATEGORY_NO,
    GAME_CODE
)
REFERENCES CATEGORY_TABLE (
	CATEGORY_NO,
    GAME_CODE
);



ALTER TABLE PATCHNOTE ADD CONSTRAINT FK_PATCH_GAME_CODE FOREIGN KEY (
	GAME_CODE
)
REFERENCES GAME_CODE (
	GAME_CODE
);

ALTER TABLE REPLY ADD CONSTRAINT FK_REPLY_USER_NO FOREIGN KEY (
	USER_NO
)
REFERENCES LOG_GG_USER (
	USER_NO
);

ALTER TABLE REPLY ADD CONSTRAINT FK_REPLY_BOARD_NO FOREIGN KEY (
    BOARD_NO
) 
REFERENCES BOARD (
    BOARD_NO
);

ALTER TABLE WEAPON ADD CONSTRAINT FK_WEAPON_ITEM_INFO FOREIGN KEY (
	ITEM_NO,
    CATEGORY_NO
)
REFERENCES BAG_ITEM_INFO (
	ITEM_NO,
    CATEGORY_NO
);

ALTER TABLE ITEM_LOG ADD CONSTRAINT FK_ITEM_LOG_ITEM_NO FOREIGN KEY (
	ITEM_NO
)
REFERENCES ITEM_LIST (
	ITEM_NO
);

ALTER TABLE ITEM_LOG ADD CONSTRAINT FK_ITEM_LOG_BOX_NO FOREIGN KEY (
	BOX_NO
)
REFERENCES Box_LIST (
	BOX_NO
);

ALTER TABLE CHAMP_SKIN_INFO ADD CONSTRAINT FK_SKIN_CHAMP_NO FOREIGN KEY (
	CHAMP_NO
)
REFERENCES CHAMP_INFO (
	CHAMP_NO
);

ALTER TABLE ATTACH_FILE ADD CONSTRAINT FK_ATTACH_BOARD_NO FOREIGN KEY (
	BOARD_NO
)
REFERENCES BOARD (
	BOARD_NO
) ON DELETE CASCADE;

ALTER TABLE ATTACH_FILE ADD CONSTRAINT FK_ATTACH_GAME_CODE FOREIGN KEY (
	GAME_CODE
)
REFERENCES GAME_CODE (
	GAME_CODE
);

ALTER TABLE ITEM_WEIGHT ADD CONSTRAINT FK_WEIGHT_ITEM_NO FOREIGN KEY (
	ITEM_NO
)
REFERENCES ITEM_LIST (
	ITEM_NO
);

ALTER TABLE ITEM_WEIGHT ADD CONSTRAINT FK_WEIGHT_BOX_NO FOREIGN KEY (
	BOX_NO
)
REFERENCES Box_LIST (
	BOX_NO
);

ALTER TABLE MAP_MARKER ADD CONSTRAINT FK_MARKER_MAP_NO FOREIGN KEY (
	MAP_NO
)
REFERENCES MAP_INFO (
	MAP_NO
);

ALTER TABLE MAP_MARKER ADD CONSTRAINT FK_MARKER_CATEGORY_NO FOREIGN KEY (
	CATEGORY_NO
)
REFERENCES MARKER_CATEGORY (
	CATEGORY_NO
);

ALTER TABLE PARTY_RECRUIT ADD CONSTRAINT FK_PARTY_BOARD_NO FOREIGN KEY (
	BOARD_NO
)
REFERENCES BOARD (
	BOARD_NO
);

ALTER TABLE TALENT_INFO ADD CONSTRAINT FK_TALENT_RUNE_NO FOREIGN KEY (
	RUNE_NO
)
REFERENCES RUNE_INFO (
	RUNE_NO
);

ALTER TABLE BAG_ITEM_INFO ADD CONSTRAINT FK_BAG_INFO_CATEGORY_NO FOREIGN KEY (
	CATEGORY_NO
)
REFERENCES BAG_ITEM_CATEGORY (
	CATEGORY_NO
);

ALTER TABLE EQUIPMENT ADD CONSTRAINT FK_EQUIP_ITEM_INFO FOREIGN KEY (
	ITEM_NO,
    CATEGORY_NO
)
REFERENCES BAG_ITEM_INFO (
	ITEM_NO,
    CATEGORY_NO
);


ALTER TABLE ITEM_COMPATIBILITY ADD CONSTRAINT FK_COMPAT_ITEM_INFO FOREIGN KEY (
	ITEM_NO,
    CATEGORY_NO
)
REFERENCES BAG_ITEM_INFO (
	ITEM_NO,
    CATEGORY_NO
);

ALTER TABLE HERO_SKIN_INFO ADD CONSTRAINT FK_SKIN_HERO_NO FOREIGN KEY (
	HERO_NO
)
REFERENCES HERO_INFO (
	HERO_NO
);

ALTER TABLE REPORT ADD CONSTRAINT FK_REPORT_USER_NO FOREIGN KEY (
	USER_NO
)
REFERENCES LOG_GG_USER (
	USER_NO
);

ALTER TABLE REPORT ADD CONSTRAINT FK_REPORT_BOARD_NO FOREIGN KEY (
	BOARD_NO
)
REFERENCES BOARD (
	BOARD_NO
);

ALTER TABLE REPORT ADD CONSTRAINT FK_REPORT_REPLY_NO FOREIGN KEY (
	REPLY_NO
)
REFERENCES REPLY (
	REPLY_NO
);

ALTER TABLE INQUIRY ADD CONSTRAINT FK_INQUIRY_USER_NO FOREIGN KEY (
	USER_NO
)
REFERENCES LOG_GG_USER (
	USER_NO
);

ALTER TABLE CATEGORY_TABLE ADD CONSTRAINT FK_CATEGORY_GAME_CODE FOREIGN KEY (
	GAME_CODE
)
REFERENCES GAME_CODE (
	GAME_CODE
);

ALTER TABLE REPLY_LIKES ADD CONSTRAINT FK_RLIKES_REPLY_NO FOREIGN KEY (
	REPLY_NO
)
REFERENCES REPLY (
	REPLY_NO
);

ALTER TABLE REPLY_LIKES ADD CONSTRAINT FK_RLIKES_USER_NO FOREIGN KEY (
	USER_NO
)
REFERENCES LOG_GG_USER (
	USER_NO
);

CREATE INDEX IDX_BOARD_POST_DATE ON BOARD(POST_DATE DESC);
CREATE INDEX IDX_REPLY_BOARD_NO ON REPLY(BOARD_NO);

-- 스킬 테이블 추가
CREATE TABLE CHAMP_SKILLS_INFO (
    CHAMP_NO NUMBER NOT NULL,
    
    SKILL_P_NAME    VARCHAR2(100)   NOT NULL,
    SKILL_P_DESC    VARCHAR2(1000),
    SKILL_P_IMG     VARCHAR2(500),
    
    SKILL_Q_NAME    VARCHAR2(100)   NOT NULL,
    SKILL_Q_DESC    VARCHAR2(1000),
    SKILL_Q_IMG     VARCHAR2(500),    
   
    SKILL_W_NAME    VARCHAR2(100)   NOT NULL,
    SKILL_W_DESC    VARCHAR2(1000),
    SKILL_W_IMG     VARCHAR2(500),
   
    SKILL_E_NAME    VARCHAR2(100)   NOT NULL,
    SKILL_E_DESC    VARCHAR2(1000),
    SKILL_E_IMG     VARCHAR2(500),
    
    SKILL_R_NAME    VARCHAR2(100)   NOT NULL,
    SKILL_R_DESC    VARCHAR2(1000),
    SKILL_R_IMG     VARCHAR2(500)
    
    
);
ALTER TABLE CHAMP_SKILLS_INFO ADD CONSTRAINT PK_CHAMP_SKILLS PRIMARY KEY (
    CHAMP_NO
);

ALTER TABLE CHAMP_SKILLS_INFO ADD CONSTRAINT FK_CHAMP_SKILLS FOREIGN KEY (
    CHAMP_NO
) REFERENCES CHAMP_INFO (CHAMP_NO) ON DELETE CASCADE;

CREATE TABLE HERO_SKILLS_INFO (
    HERO_NO         NUMBER          NOT NULL,
    
    SKILL_LCLICK_NAME    VARCHAR2(100)   NOT NULL, 
    SKILL_LCLICK_DESC    VARCHAR2(1000),
    SKILL_LCLICK_IMG     VARCHAR2(500),
    
    SKILL_RCLICK_NAME    VARCHAR2(100),  
    SKILL_RCLICK_DESC    VARCHAR2(1000),
    SKILL_RCLICK_IMG     VARCHAR2(500),
    
    SKILL_SHIFT_NAME VARCHAR2(100),  
    SKILL_SHIFT_DESC    VARCHAR2(1000),
    SKILL_SHIFT_IMG     VARCHAR2(500),
    
    SKILL_E_NAME     VARCHAR2(100), 
    SKILL_E_DESC    VARCHAR2(1000),
    SKILL_E_IMG     VARCHAR2(500),
    
    SKILL_Q_NAME     VARCHAR2(100)  NOT NULL,
    SKILL_Q_DESC    VARCHAR2(1000),
    SKILL_Q_IMG     VARCHAR2(500)
);

ALTER TABLE HERO_SKILLS_INFO ADD CONSTRAINT PK_HERO_SKILLS PRIMARY KEY (
    HERO_NO
);

ALTER TABLE HERO_SKILLS_INFO ADD CONSTRAINT FK_HERO_SKILLS FOREIGN KEY (
    HERO_NO
) REFERENCES HERO_INFO (HERO_NO) ON DELETE CASCADE;
------------------
-- 시퀀스 생성
CREATE SEQUENCE SEQ_USER_NO START WITH 1 INCREMENT BY 1 NOCACHE;     -- 유저 번호
CREATE SEQUENCE SEQ_BOARD_NO START WITH 1 INCREMENT BY 1 NOCACHE;    -- 게시글 번호
CREATE SEQUENCE SEQ_REPLY_NO START WITH 1 INCREMENT BY 1 NOCACHE;    -- 댓글 번호
CREATE SEQUENCE SEQ_LOG_NO START WITH 1 INCREMENT BY 1 NOCACHE;   -- 아이템 로그 번호
CREATE SEQUENCE SEQ_REPORT_NO START WITH 1 INCREMENT BY 1 NOCACHE; -- 신고 번호
CREATE SEQUENCE SEQ_INQUIRY_NO START WITH 1 INCREMENT BY 1 NOCACHE; -- 문의 번호
CREATE SEQUENCE SEQ_CATEGORY_NO START WITH 1 INCREMENT BY 1 NOCACHE; -- 카테고리 번호
CREATE SEQUENCE SEQ_FILE_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_NOTICE_NO START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE SEQ_RUNE_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ITEM_NO START WITH 1 INCREMENT BY 1 NOCACHE; 
CREATE SEQUENCE SEQ_CHAMP_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CHAMP_SKIN_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_SPELL_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TALENT_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_HERO_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_HERO_SKIN_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_MARKER_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_MAP_NO START WITH 1 INCREMENT BY 1 NOCACHE;

-- 게임 코드 
INSERT INTO GAME_CODE (GAME_CODE, GAME_NAME) VALUES ('LOL', 'League of Legends');
INSERT INTO GAME_CODE (GAME_CODE, GAME_NAME) VALUES ('BG', 'PUBG: BATTLEGROUNDS');
INSERT INTO GAME_CODE (GAME_CODE, GAME_NAME) VALUES ('OW', 'Overwatch 2');

-- 추가적인 컬럼
ALTER TABLE LOL_ITEM_INFO ADD ITEM_TAG VARCHAR2(500);
COMMENT ON COLUMN LOL_ITEM_INFO.ITEM_TAG IS '아이템 태그';
ALTER TABLE LOG_GG_USER ADD EMAIL VARCHAR2(255);
COMMENT ON COLUMN LOG_GG_USER.EMAIL IS '이메일';